### ISSUE TITLE
apply resource in K8s, pod 0/1 log: undefined symbol: cndevGetCardHeartbeatCoun

### ISSUE THREAD

**Issue by luanshuo** [Cambricon/mlu-exporter#3]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._
virsion: v2.0.11
rpm:
![image](https://github.com/Cambricon/cambricon-k8s-device-plugin/assets/56577113/f8a3691f-d01a-47a6-ba9b-4831bcb5418b)

ldd -r mlud-exporter
![image](https://github.com/Cambricon/cambricon-k8s-device-plugin/assets/56577113/03b5964d-dade-429a-9fb5-d047db6b4b39)

log:
![image](https://github.com/Cambricon/cambricon-k8s-device-plugin/assets/56577113/53180571-bac0-4fd0-ab01-09140e76f629)

sys version: 
![image](https://github.com/Cambricon/cambricon-k8s-device-plugin/assets/56577113/9eb32c6c-5bb8-43e2-a9e5-1f53215514fd)

cnmon
![image](https://github.com/Cambricon/cambricon-k8s-device-plugin/assets/56577113/2f3818b5-8d16-4936-a38a-ff58a01e5613)

**Comment by rayroot** [comment]
It seems to be a compilation-related issue. Please refer to the compilation scripts in the repository and try building a container image. 

If the problem persists, please provide more information k8s version, docker version, host info and ways to reproduce this issue as detailed as possible.

**Comment by luanshuo** [comment]
> It seems to be a compilation-related issue. Please refer to the compilation scripts in the repository and try building a container image.
> 
> If the problem persists, please provide more information k8s version, docker version, host info and ways to reproduce this issue as detailed as possible.

镜像构建步骤为 :
1、sed -i "s/docker/nerdctl -n buildkit/g" build_image.sh
2、GOPROXY=https://goproxy.cn ./build_image.sh

当前环境为：
1、驱动版本
![image](https://github.com/Cambricon/mlu-exporter/assets/56577113/cfdcdb1c-e9d4-4939-8205-8369524eb34c)

2、nerdctl版本
![image](https://github.com/Cambricon/mlu-exporter/assets/56577113/ce85a1f5-a4bf-4bd7-a8d6-993444454b15)

3、conrainerd
![image](https://github.com/Cambricon/mlu-exporter/assets/56577113/81ee48ae-f386-41a5-85ec-738b35699e77)


4、k8s版本
![image](https://github.com/Cambricon/mlu-exporter/assets/56577113/6bcb8c1b-685b-4cb1-86e5-eafaf2809ba0)

5、驱动校验
![image](https://github.com/Cambricon/mlu-exporter/assets/56577113/ab8d8dfc-59e1-4608-a86c-d233e2b92b24)

plugin的运行情况：
<img width="1198" alt="image" src="https://github.com/Cambricon/mlu-exporter/assets/56577113/f1158fc6-cf44-4e91-8a93-874b9ed02022">

**Comment by rayroot** [comment]
cndev version ?

**Comment by kldancer** [comment]
@luanshuo 请问你解决了吗

**Comment by rayroot** [comment]
使用的 cndev 版本跟镜像基础操作系统不一致导致，已解决
