### ISSUE TITLE
undefined symbol: cndevGetCardHeartbeatCount

### ISSUE THREAD

**Issue by Tokisaki-Github** [Cambricon/mlu-exporter#4]
你好，

最近在使用mlu370-x8时，希望使用mlu-exporter进行监控。版本信息如下：
```
Driver: v5.10.22
Cndev : 3.8.2
OS: Kylin v10
Docker: 19.0.3
```

使用最新v2.0.14和v2.0.11版本均报错undefined symbol: cndevGetCardHeartbeatCount

经过查询，3.8.2的libcndev.so并不包含cndevGetCardHeartbeatCount
```
(base) [root@localhost lib64]# nm -D /usr/local/neuware/lib64/libcndev.so | grep cndevGetCard*
000000000006b300 T cndevGetCardHealthState
0000000000072080 T cndevGetCardName
00000000000997f0 T cndevGetCardNameString
00000000000a8d40 T cndevGetCardNameStringByDevId
00000000000722f0 T cndevGetCardSN
0000000000068be0 T cndevGetCardVfState
```

希望能够适配，谢谢。

**Comment by rayroot** [comment]
请使用 `CHANGELOG ` 中提示的 cndev 版本，代码中的 cndev.h 需要跟对应版本的 so 保持一致

**Comment by Tokisaki-Github** [comment]
> 请使用 `CHANGELOG ` 中提示的 cndev 版本，代码中的 cndev.h 需要跟对应版本的 so 保持一致

你好，我们从官网能够下载到的最新的CNToolkit是3.8.4版本，该版本中的cndev版本为3.8.2。根据changelog，应该是要2.0.8的exporter才能兼容？但是exporter发布的tag里并没有2.0.8，只有2.0.11和2.0.14。

<img width="521" alt="image" src="https://github.com/user-attachments/assets/2abd9a2d-2983-43c0-97f2-bebe14b4960e">

**Comment by rayroot** [comment]
建议联系销售或者AE 获取新版的 cndev
